Menhir | Gagin Artur
Kakadu/fp2022 pull request #17
Opened 2022-11-19 18:57 UTC by lastdesire

Сделал документашку в виде pdf-ки, чтобы хоть как-то компенсировать свой sh1t-code.  По моим ощущениям здесь много лютых способов изобрести велосипед, простите за это, но я правда стараюсь...

2022-11-19 20:05 UTC, Kakadu commented
> Сделал документашку в виде pdf-ки, чтобы хоть как-то компенсировать свой sh1t-code. По моим ощущениям здесь много лютых способов изобрести велосипед, простите за это, но я правда стараюсь...

Грамматика на странице 4 неправильная какая-то. У того, что вверху лишний первый main, хотя я не уверен, что делать правила такими плоскими -- это хорошая идея. У того, что пониже, слишком богатое AST: оно описывает деревья произвольной вложенности, в то время как у вас она вроде как ограниченая. Возможно, вы разрешили писать "или" в правой части правила, но для минимального эксперимента, чтобы сдать пораньше -- это оверкилл.

2022-11-19 20:07 UTC, Kakadu commented
.DS_Store в игнор

2022-11-19 20:09 UTC, Kakadu commented on Menhir/lib/ast.ml
> +  | Nonterm of string * parse_tree list
А, погодите. Может имелось в виду, что тип этот -- это результат запуска интерпретатора?

2022-11-19 20:16 UTC, lastdesire commented on Menhir/lib/ast.ml
> +  | Nonterm of string * parse_tree list
Если я Вас правильно понял, то да: parse_tree получается для каждой цепочки токенов, которую пользователь вводит. А grammar -- это то, что находится в файле .mly. По-моему, самый верхний main  на 4 странице не является лишним, потому что это start rule.

2022-11-19 20:27 UTC, Kakadu requested changes
Что-то я офигеваю от того, что вижу...

2022-11-19 20:27 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
В камле есть модуль Arg...

2022-11-19 20:27 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
И какова сложность этой фнукции?

2022-11-19 20:27 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +    if not (String.equal h symbol) then is_string_list_contains_symbol symbol tl else true
гварды?*

2022-11-19 20:27 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +  \    | INT"
Прочитайте про quoted string literals
https://v2.ocaml.org/manual/lex.html#sss:stringliterals

2022-11-19 20:27 UTC, Kakadu commented on Menhir/lib/parser.ml
> +
Погодите, вы ж вроде должны были парсер написать на менхире или комбинаторах? Что за штуку я вижу тут?

2022-11-19 20:29 UTC, Kakadu commented on Menhir/lib/ast.ml
> +  | Nonterm of string * parse_tree list
Я просто подумал, что стартовых нетерминалов может быть много, и запутался. Но если он один, то ОК

2022-11-19 20:36 UTC, lastdesire commented on Menhir/lib/parser.ml
> +
Парсер мною писался вообще сразу практически, как я погрузился в OCaml, поэтому он здесь ужасен. Плакать даже хочется. То есть у меня парсер грамматики menhir'а должен быть на menhir'е?)

2022-11-19 20:39 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +    if not (String.equal h symbol) then is_string_list_contains_symbol symbol tl else true
А здесь что-то может пойти не так?

2022-11-20 09:30 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +    if not (String.equal h symbol) then is_string_list_contains_symbol symbol tl else true
просто можно чище написать

2022-11-20 09:30 UTC, Kakadu commented on Menhir/lib/parser.ml
> +
Или на комбинаторах

2022-11-20 14:23 UTC, lastdesire commented on Menhir/lib/parser.ml
> +
Неплохая ночь и сегодняшний день вышел (и продолжается): я примерно разобрался, как юзать Menhir. В качестве лексера использовал sedlex. Там все еще костыль с делением файла на две части: до "%%" и после, но настолько ли он плох? Это облегчает парсинг, но если надо пофиксить, то как-нибудь сделаю. Пока что не ловил никаких исключений, которые могут произойти при парсинге, но займусь этим в ближайшее время.

2022-11-20 16:11 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Поправлю...

2022-11-20 16:42 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Убрал новую проверку на длину списка при каждом рекурсивном вызове (это было реально плохо). Сложно сказать, стало ли лучше. Можно ли быстрее?

2022-11-22 22:32 UTC, Kakadu reviewed
Это всё страшновато, но для ранней сдачи пойдет.

2022-11-22 22:32 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Стало лучше. 
А вообще, вам точно нужно брать последние элементы? Список не очень приспособлен к обходы с хвоста...

2022-11-22 22:32 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +        match allNonterminalsOfRule with
https://www.youtube.com/watch?v=ZsHMHukIlJY&t=1393s
У меня не хватили терпения дочитать идентификатор до конца.)

2022-11-22 22:32 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +          else getNewInputIfNonterminalRuleIsFits tl' remaining_input_len
Сделайте короче!

2022-11-22 22:32 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +      if List.length new_input = List.length input
List.compare_lengths?

2022-11-22 22:33 UTC, Kakadu commented
Сделайте rebase, а то не мержится.

2022-11-23 15:30 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +      if List.length new_input = List.length input
Поправил.

2022-12-08 16:24 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +        match allNonterminalsOfRule with
Поправил имена, по моим ощущениям стало получше.

2022-12-08 16:24 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +          else getNewInputIfNonterminalRuleIsFits tl' remaining_input_len
Залагал, сделал более адекватно.

2022-12-08 16:27 UTC, lastdesire commented
Сделал rebase и разобрался с DCO (правда коммиты для него пустые, вроде, это плохой тон, но сообразил уже после того, как сделал, теперь буду иметь в виду, извините). Сейчас работаю над обработкой ошибок.

2022-12-17 20:19 UTC, lastdesire commented
Теперь умею ловить все ошибки. Потихоньку пишу больше тестов. Обновил информацию о проекте. Дальше по плану до конца изучить Arg модуль.

2022-12-18 11:36 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +    if not (String.equal h symbol) then is_string_list_contains_symbol symbol tl else true
Полагаю, теперь стало лучше.

2022-12-18 18:21 UTC, lastdesire commented
Добавил еще парочку тестов + тестил сам ручками. Исправил ошибки линтера, остались только те, которые, полагаю, можно не фиксить (от парсера и от мутабельных переменных, нужных для использования модуля Arg).

2022-12-18 18:25 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Готово!

2022-12-21 21:05 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +
Я вот смотрю на эти три функции... Не получится ли, что оно лишний раз всё парсит, когда Вы их вызываете?

2022-12-21 21:07 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +   %token EOL\n\
`{| ... |}`

2022-12-21 21:17 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
List.mem?

2022-12-21 21:17 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +      if String.equal (List.hd input) h
Почему не мэтчинг по input?

2022-12-21 22:10 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
А вот и велосипед, исправил, спасибо :)

2022-12-21 22:10 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +   %token EOL\n\
Опять забыл, хотя недавно читал, мда. Поправил.

2022-12-21 22:25 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +      if String.equal (List.hd input) h
Ветка с мэтчингом h :: tl будет очень большой, что, как мне кажется, сделает эту функцию, где я применяю проверку, как и требовалось, "в лоб", еще менее читаемой.

2022-12-21 23:47 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +
Это правда. Поправил. Теперь несколько сложных функций принимают еще один аргумент `parse_res`, который является кортежем из токенов, стартового правила, грамматики. Хороший пример того, что лучше сначала подумать несколько раз, а потом уже написать код, потому что исправлять это было достаточно тяжело (требовалась высокая внимательность).

2022-12-23 13:46 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +      if String.equal (List.hd input) h
Вы всё-таки попробуйте, вдруг читаемостьповысится...

2022-12-23 13:47 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +
Вообще, внимательность не должна требоваться. У Вас должны  разползаться типы, везде где надо исправлять.

2022-12-23 13:51 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Может можно ещё короче?

2022-12-23 13:53 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Оно где-то используется?

2022-12-23 13:57 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +                 parse_res
Почему нельзя было сделать одну функцию для применения правила, которая бы либо давала и результат, и неразобранный вход, либо сообщала бы ошибку? Т.е. так, как парсер-комбинаторы работают.
Так у вас бы осталось в 2 раза меньше функций для применения правил, и разрулился бы костыль с доставанием из хвоста списка.

2022-12-23 13:59 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +let gen_tree_parser text parse_res = parse_tree text parse_res
Тоже можно короче.

2022-12-23 14:05 UTC, Kakadu reviewed
Там вроде ещё не все пукты из задания сделаны.

2022-12-23 14:05 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +            about required syntax."
Всё-таки sprintf читается лучше

2022-12-23 16:19 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Нет, удаляем!

2022-12-23 16:19 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +
Может, это потому что я ночью исправлял. По сути, так и получилось.

2022-12-23 16:21 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Действительно: `Base.List.mem list symbol ~equal:(fun x y -> String.equal x y)`. Исправил.

2022-12-23 20:56 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +            about required syntax."
Соглашусь, изменил.

2022-12-23 21:05 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +            about required syntax."
Пункт про левую рекурсию пока что опустил, потому что не уверен, что успею до нового года. Стараюсь пока что устранить текущие код-стайл проблемы, далее уже выжимать из себя максимум (успею --- славно, нет --- надеюсь на Вашу милость снять с меня парочку баллов, которые, может, компенсируют баллы за летучки).

2022-12-23 21:08 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +let gen_tree_parser text parse_res = parse_tree text parse_res
Объединил в одну функцию, если речь об этом.

2022-12-23 21:28 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +      if String.equal (List.hd input) h
Ладно, это, все-таки, повышает читаемость, стоило сначала попробовать, потом утверждать, простите.

2022-12-23 22:23 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +                 parse_res
Теперь функция try_apply_rule возвращает и remaining_input, что избавляет от использования костыля.

2022-12-25 10:08 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +            about required syntax."
Вероятно, надо допилить вот это, помержить, а остальное  в следующем PR

2022-12-25 10:09 UTC, Kakadu commented on Menhir/REPL.ml
> +  else ();
:)

2022-12-25 10:11 UTC, Kakadu commented on Menhir/REPL.ml
> +  if (not (Array.length Sys.argv = 2)) || not (String.equal Sys.argv.(1) "help")
По массивам тоже можно мэтчиться

2022-12-25 10:13 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +  in
:(

2022-12-25 10:15 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +    match start_nonterms with
Думаю,  если поменять местами аргументы -- будет короче

2022-12-25 10:17 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Я в предыдущем комменте имел вв иду каррирование

2022-12-25 10:18 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Сделайте ещё cram тесты как в директории demos. Почитать грамматику из файла и распарсить токены капсом не должно быть большой проблемой.

2022-12-25 10:19 UTC, Kakadu commented on Menhir/lib/parser.mly
> +%token SEMICOLON (* ; *)
Там можно задавать имена короткие токенам и использовать их ниже

> %token SEMICOLON ";"

2022-12-26 12:15 UTC, lastdesire commented on Menhir/lib/parser.mly
> +%token SEMICOLON (* ; *)
Удобненько.

2022-12-26 12:16 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Понял, сделал.

2022-12-26 12:23 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +  in
Теперь :)

2022-12-26 12:26 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +    match start_nonterms with
Done.

2022-12-26 12:48 UTC, lastdesire commented on Menhir/REPL.ml
> +  else ();
:)

2022-12-26 12:48 UTC, lastdesire commented on Menhir/REPL.ml
> +  if (not (Array.length Sys.argv = 2)) || not (String.equal Sys.argv.(1) "help")
Круто, убрал этот sh1t-code

2022-12-26 16:09 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +            about required syntax."
Долговато что-то я думал над алгоритмом, но сделал.

2022-12-26 16:16 UTC, lastdesire commented
Пофиксил все замечания, добавил устранение левой рекурсии. Предлагаю мерджить, в следующем пр добавлю cram тесты.

2022-12-29 13:12 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
В следующем пулл реквесте добавлю.

2022-12-29 18:34 UTC, lastdesire commented
Добавил cram тесты, однако пока что над одним файлом. Правильно ли я понимаю, что мне следует в папку demo_inputs закинуть еще парочку файлов с разной грамматикой, а затем протестить на парсинг?

2022-12-29 20:08 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
А в каких случаях передается name = "", что второй случай get_h_string_list влияет?

2022-12-29 20:08 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Это List.filter такой?

2022-12-29 20:16 UTC, Kakadu reviewed
вы так те 2 функции не объединили?

2022-12-29 20:16 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Это тоже filter_map какой-то

2022-12-29 20:16 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Снова какой-то filter

2022-12-29 20:16 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
А вообще, разве `A -> epsilon` всегда можно удалять?

2022-12-29 20:16 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +(*>>>>>>>>>>>>>>>>>>>>>>>>> +++++++++++++++++++++++++++++ <<<<<<<<<<<<<<<<<<<<<<<<<*)
Такие разделители вообще не принято делать. Ни в каком языке

2022-12-29 20:17 UTC, Kakadu commented
> Пофиксил все замечания, добавил устранение левой рекурсии. Предлагаю мерджить, в следующем пр добавлю cram тесты.

Сделайте тест, чтобы было очевидно, что устранение левой есть

2022-12-30 10:51 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +(*>>>>>>>>>>>>>>>>>>>>>>>>> +++++++++++++++++++++++++++++ <<<<<<<<<<<<<<<<<<<<<<<<<*)
Рядовой изобретатель увлекся.

2022-12-30 10:57 UTC, lastdesire commented on Menhir/demos/interpretTests.t
> +   [ main :  [ expr :  INT   [ expr' :  MULTY   [ expr :  INT  ]  ]  ]   EOL  ]
> > Пофиксил все замечания, добавил устранение левой рекурсии. Предлагаю мерджить, в следующем пр добавлю cram тесты.
> 
> Сделайте тест, чтобы было очевидно, что устранение левой есть

Сделанные cram тесты как раз демонстрируют это, например:
`INT MULTY INT EOL` --- правило вида `expr: [expr; MULTY; expr]`

2022-12-30 11:00 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
> > Пофиксил все замечания, добавил устранение левой рекурсии. Предлагаю мерджить, в следующем пр добавлю cram тесты.
> 
> Сделайте тест, чтобы было очевидно, что устранение левой есть

Вот обычные тесты, их я добавил сразу же, вместе с устранением левой рекурсии, например: 
`INT PLUS INT` --- правило вида `expr: [expr; PLUS; expr]`

2022-12-30 11:09 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Это не правда, они имеют место быть в грамматике. Затуп. Исправил.

2022-12-30 11:09 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Действительно, проще через List.filter.

2022-12-30 11:13 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Я уже много раз с подобными штуками сталкивался в этом проекте, то есть: я действительно, по сути, пишу велосипед (например, сам изобретаю фильтрацию, вместо того, чтобы воспользоваться готовой функцией). Отсюда мой вопрос: это вообще нормально? Как мне сразу понимать, что лучше использовать такую-то функцию? Или это приходит с опытом, а моя задача --- впитывать этот самый опыт?

2022-12-30 12:27 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Вообще, это never happen ситуация, поскольку я при парсинге устраняю это. Просто, чтобы варнингов не было.

2022-12-30 12:49 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Переделал.

2022-12-30 13:30 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Здесь мне `helper` не засунуть в filter_map, вроде? Я хочу с помощью этой функции получить список нетерминалов, которые не повторяются.

2022-12-30 13:37 UTC, lastdesire commented
> вы так те 2 функции не объединили?

Просто я пытаюсь понять, с какой целью?
Предположим, что я хочу попробовать применить одно из следующих правил:
```
main:
| X; TOKEN_1
| X; TOKEN_2
| ...
| X; TOKEN_n
```
 к инпуту пользователя `X TOKEN_n`. 
 * Что происходит в моем случае: Я делаю `n` проверок, после чего один раз строю дерево к последнему правилу. 
 * Что будет при объединении этих функций: Я буду делать `n` проверок, вместе с которыми я `n - 1` раз построю <<недодерево>>, которое не пригодится, после чего еще один раз построю дерево к последнему правилу.

2023-01-02 02:10 UTC, lastdesire commented
В общем, я подумал, что я и без этого замучил Вас с проверками, поэтому решил просто сделать то, что сказано. Почему-то я долго страдал над этими изменениями, хотя отредаченного кода не очень много вышло. Словил другую проблему теперь: при устранении левой рекурсии вывод происходит с новыми правилами, например: вместо 
`[ main :  [ expr :  [ expr: INT ]  PLUS. [ expr :  INT  ]  ]   EOL  ]`
`[ main :  [ expr :  INT   [ expr' :  PLUS   [ expr :  INT  ]  ]  ]   EOL  ]`. 
Насколько это критично и необходимо для изменений --- хороший вопрос, однако сегодня я что-то устал, да и в пять часов утра не будет никакого смысла спрашивать Вас об этом в чате, поэтому узнаю завтра.

2023-01-02 14:25 UTC, Kakadu commented on Menhir/demos/interpretTests.t
> +  > demo_inputs/demo_input.mly
А он правда имя файла с грамматикой со stdio принимает слитно с токенами? Не проще было бы опцию командной строки сделать?

2023-01-02 14:28 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Я думаю, это порнография. Вы за этой херней прячете то, что список всегда непустой, и тот, кто будет с Вашего кода потом списывать, будет Вас проклинать.

2023-01-02 14:29 UTC, lastdesire commented on Menhir/demos/interpretTests.t
> +  > demo_inputs/demo_input.mly
Он принимает их по лайнам. Каждый аргумент нормально считывается через 
`let read_command () =
  try read_line () with
  | End_of_file -> ""
;;`, вроде как.

2023-01-02 14:30 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Ну тогда fold. И нужно множество, наверное, а не список.

2023-01-02 14:33 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Это интересный вопрос, чтобы обсудить со всеми
1) Может вас заставляли на 1 курсе всё с нуля писать, и вы продолжаете
2) Может и правда забываете, что только что это уже писали.
3) Может подсознательно Вам стрёмно скоращать код, так как измеряете работу в количестве строчек.

2023-01-02 14:38 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +  Stdio.In_channel.input_all (Unix.in_channel_of_descr file_path)
In_channel.read_all ?

2023-01-02 14:38 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +  Stdio.In_channel.input_all (Unix.in_channel_of_descr file_path)
Мне вот интересно, почему  этот код родился.

2023-01-02 14:39 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +     | _ :: _ when string_list_contains h (get_nonterminals grammar) (* NONTERM SYMBOL *)
Думаю, это стоит вынести выше, чтобы не вычислялось повторно

2023-01-02 14:41 UTC, Kakadu commented on Menhir/lib/interpret.ml
> +;;
Может всё-таки какой-нить Stdlib.List.mem? B вообще, тут должен быть Set

2023-01-02 14:42 UTC, Kakadu commented on Menhir/demos/interpretTests.t
> +  > demo_inputs/demo_input.mly
Это попахивает извращением, ну да ладно

2023-01-02 14:43 UTC, Kakadu reviewed
Вроде гораздо лучше, чем было в начале. Сколько там доделать осталось?

2023-01-02 14:44 UTC, lastdesire commented
> Вроде гораздо лучше, чем было в начале. Сколько там доделать осталось?

Таски все выполнены, вроде? Только пофиксить грязь оставшуюся надо?

2023-01-02 14:59 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +     | _ :: _ when string_list_contains h (get_nonterminals grammar) (* NONTERM SYMBOL *)
Вынес + убрал `text` в этой функции (он был не нужен)

2023-01-02 15:06 UTC, lastdesire commented on Menhir/demos/interpretTests.t
> +  > demo_inputs/demo_input.mly
:)

2023-01-02 15:13 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +  Stdio.In_channel.input_all (Unix.in_channel_of_descr file_path)
Пофиксил. Либо я на сервере в Дискорде такой ответ получил, либо у кого-то в домашке увидел (вроде, все-таки, последний вариант :Р).

2023-01-02 15:14 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Будем стараться привыкать, что поделать)

2023-01-02 15:35 UTC, lastdesire commented on Menhir/lib/interpret.ml
> +;;
Сделал через `List.fold_left`.

2023-01-02 17:10 UTC, Kakadu commented
> > Вроде гораздо лучше, чем было в начале. Сколько там доделать осталось?
> 
> Таски все выполнены, вроде? Только пофиксить грязь оставшуюся надо.

Не помню. Перепроверьте

2023-01-02 17:30 UTC, lastdesire commented
> > > Вроде гораздо лучше, чем было в начале. Сколько там доделать осталось?
> > 
> > 
> > Таски все выполнены, вроде? Только пофиксить грязь оставшуюся надо.
> 
> Не помню. Перепроверьте

Ну вот я как раз и посмотрел, перед тем, как написать Вам комментарий)

2023-01-02 17:55 UTC, Kakadu commented
> * трансляция в парсер-комбинаторы (+, заюзал Menhir)

А причем тут menhir?

2023-01-02 18:09 UTC, lastdesire commented
> > * трансляция в парсер-комбинаторы (+, заюзал Menhir)
> 
> А причем тут menhir?
> 
> C остальными 3мя пунктами согласен



> > * трансляция в парсер-комбинаторы (+, заюзал Menhir)
> 
> А причем тут menhir?
> 
> C остальными 3мя пунктами согласен

Может я в другом виде данный пункт трактую? Сначала я сделал вообще самодельный парсер грамматики, где был лютый sh1t-код, потом Вы сказали переделать его как раз на парсер-комбинаторах или Menhir'е, где я выбрал последнее.

2023-01-02 18:18 UTC, Kakadu commented
> > > * трансляция в парсер-комбинаторы (+, заюзал Menhir)
> > 
> > 
> > А причем тут menhir?
> > C остальными 3мя пунктами согласен
> 
> > > * трансляция в парсер-комбинаторы (+, заюзал Menhir)
> > 
> > 
> > А причем тут menhir?
> > C остальными 3мя пунктами согласен
> 
> Может я в другом виде данный пункт трактую? Сначала я сделал вообще самодельный парсер грамматики, где был лютый sh1t-код, потом Вы сказали переделать его как раз на парсер-комбинаторах или Menhir'е, где я выбрал последнее.

Имелось в виду трансляции минименхира  в функцию-парсер-комбинатор, которая будет парсить

2023-01-02 18:27 UTC, lastdesire commented
> 

Вот оно как. То есть я еще должен уметь выдавать `.ml`, где будет функция-парсер-комбинатор для описанной грамматики. Жизнь полна боли. :)

2023-01-02 18:27 UTC, lastdesire commented
> Имелось в виду трансляции минименхира в функцию-парсер-комбинатор, которая будет парсить

Вот оно как. То есть я еще должен уметь выдавать `.ml`, где будет функция-парсер-комбинатор для описанной грамматики. Жизнь полна боли. :)

2023-01-02 18:28 UTC, Kakadu commented
> > Имелось в виду трансляции минименхира в функцию-парсер-комбинатор, которая будет парсить
> 
> Вот оно как. То есть я еще должен уметь выдавать `.ml`, где будет функция-парсер-комбинатор для описанной грамматики. Жизнь полна боли. :)

Можно компилировать грамматику в парсер правильного типа и потом запускать. Без генерации .ml

2023-01-02 18:29 UTC, Kakadu commented
Давайте только вначале  ор линтера победим и помержим

2023-01-02 18:39 UTC, lastdesire commented
> Давайте только вначале ор линтера победим и помержим

Хорошо. Крики о мутабельных переменных в REPL.ml и о том, что что-то не так в parser.ml/parser.mli/_none_ надо убирать?

2023-01-02 19:41 UTC, lastdesire commented
Пофиксил все, кроме указанных выше.

2023-01-02 21:11 UTC, merged