OCaml with labeled and optional arguments | Denis Porsev | 4th year
Kakadu/fp2022 pull request #29
Opened 2023-01-01 23:02 UTC by bahbyega

### An implementaion of "OCaml with labeled and optional arguments" mini-language

#### Features done:

- Parser
- Interpreter
- Pretty-printing for ast types and errors
- Simple read-eval-print-loop
- Integration tests

#### Features in progress (and TODOs):

- [ ] Type inference with polymorphism is a WIP
- [ ] More thorough testing
- [ ] Documentation
- [ ] Extensions of REPL (new commands, better exception handling)

See [README](https://github.com/bahbyega/fp2022/blob/bahbyega_OCamlLabeledArgs/OCamlLabeledArgs/README.md) for more

2023-01-07 15:14 UTC, Kakadu requested changes

2023-01-07 15:14 UTC, Kakadu commented on OCamlLabeledArgs/demos/demoSingle.t
> +  - : <type_undef> = 120
Традиционно от всех требую факториал через фикс.
Типы надо печаать.

И там третий пункт в условии был "Стандартные типы (числа, списки, option)"

2023-01-07 15:14 UTC, Kakadu commented on OCamlLabeledArgs/lib/interpret.ml
> +      >>= fun arg_val ->
вам правда без let* удобнее?

2023-01-07 15:15 UTC, Kakadu commented on OCamlLabeledArgs/demos/demoSingle.t
> +
Проверьте ещё, что аргументы местами переставлять можно.

2023-01-12 22:31 UTC, bahbyega commented
Поправил замечания, дописал вывод типов, добавил в язык списки.

2023-01-13 12:09 UTC, Kakadu commented on OCamlLabeledArgs/demos/demoSingle.t
> +  - : int -> int = 4
По-моему этот тип неправильный.

2023-01-13 12:19 UTC, Kakadu commented on OCamlLabeledArgs/demos/demoSingle.t
> +  - : int -> int = 4
Я поверю, что Вы можете это исправить.

2023-01-13 12:19 UTC, merged