Ruby
Kakadu/fp2022 pull request #31
Opened 2023-01-04 11:14 UTC by illided

2023-01-04 11:57 UTC, illided commented
ref нужны для поддержки общего состояния массивов и классов

2023-01-04 22:18 UTC, Kakadu commented on Ruby/lib/ast.mli
> +  | Lambda of state * string list * ast (** Lambda [closure param_list * body]*)
А в чем разница между Function и Lambda? Напишите в комментах и тут, пжлста

2023-01-04 22:19 UTC, Kakadu commented on Ruby/lib/ast.mli
> +  | Lambda (** AnonymousFunction *)
нерекурсивные типы не должны быть рекурсивными

2023-01-04 22:21 UTC, Kakadu commented on Ruby/lib/interpret.ml
> +      let eval_step (mon : (value list * state) t) (code : ast) =
вы так выписываете типы, будто это Java

2023-01-04 22:22 UTC, Kakadu commented on Ruby/lib/interpret.ml
> +      conditional cond_v thenB elseB >>= fun branch -> eval st branch
Вам let* правда не понравился, или Вы про него забыли?

2023-01-04 22:23 UTC, Kakadu commented on Ruby/lib/interpret.ml
> +              |> List.map (fun s -> String s)))
ОЧЕНЬ СЛОЖНО

2023-01-04 22:26 UTC, Kakadu commented on Ruby/lib/interpret.ml
> +          | String suff :: _ -> return_sst (Bool (String.ends_with ~suffix:suff s))
А если там будет список в 100500 -- это не ошибка?

2023-01-04 22:28 UTC, Kakadu requested changes
Думаю, точно не помешают примеры про лямбды
* фикс
* мемеоизация https://gitlab.com/Kakadu/fp2020course-materials/-/blob/master/code/fib/lib.ml#L32
* и т.п.

2023-01-05 18:45 UTC, illided commented on Ruby/lib/ast.mli
> +  | Lambda of state * string list * ast (** Lambda [closure param_list * body]*)
Под Lambda здесю понимаются Block в руби. Вкратце это некоторый код который можно неявно передать функции в качестве последнего параметра и затем исполнять его через `yield`.
Основное отличие, что блоки наследуют локальные переменные от состояния в котором они были обьявлены, а обычные функции работают с чистым локальным состоянием. Во время парсинга это не так важно (поэтому там просто это как параметр оформлено), а вот в рантайме уже важно.
Немного исправил пример чтобы это отличие подчеркнуть. Насчет фикса и мемоизации не думаю что это можно сделать с помощью руби блоков.

2023-01-06 17:18 UTC, Kakadu commented on Ruby/lib/ast.mli
> +  | Lambda of state * string list * ast (** Lambda [closure param_list * body]*)
Но в условии же есть третий пункт?

2023-01-06 17:19 UTC, Kakadu requested changes
Я всё ещё хочу больше тестов. 
И желательно отдельный .t файл под каждый пункт условия.

2023-01-07 10:10 UTC, illided commented on Ruby/lib/ast.mli
> +  | Lambda of state * string list * ast (** Lambda [closure param_list * body]*)
Искренне верил что это имелось ввиду именно про руби блоки :)
Добавил более традиционные лямбды

2023-01-07 12:05 UTC, Kakadu requested changes

2023-01-07 12:05 UTC, Kakadu commented on Ruby/examples/combinators.rb
> +f1 = fact (5)
U это и не Y, и не Z комбинатор. Почему он вообще работает? Напишите в комментах и тут.

2023-01-07 12:05 UTC, Kakadu commented on Ruby/examples/combinators.rb
> +f2 = fact (5)
А почему Y работает -- тоже не понятно. Неужели в Ruby -- ленивая стратегия?

2023-01-07 12:05 UTC, Kakadu commented on Ruby/functions.t
> +  $ ./INTERPRET.exe ../../../../examples/combinators.rb
Там можно указать (cram (deps ...)), чтобы не писать слишком длинные пути в файлах тестов.

2023-01-07 13:02 UTC, illided commented on Ruby/examples/combinators.rb
> +f1 = fact (5)
Мы передаем в `U` карированую функцию, которая принимает функцию `g` первым аргументом. Бесконечной рекурсии не будет потому что `g` не применяется сама к себе пока мы не передадим `x`, поэтому все ок.
Когда в `fact` передают `x` мы начинаем вычислять условие, вычислять `g(g)` или игнорировать `g` если нужно.

2023-01-07 13:02 UTC, illided commented on Ruby/examples/combinators.rb
> +f2 = fact (5)
В ruby как раз не ленивая стратегия, поэтому чтобы оно работало добавлена лямбда которая не принимает никаких аргументов. По хорошему там конечно должно быть просто `g(Y(g))`

2023-01-07 13:19 UTC, Kakadu commented
Вы глобально до какой оценки планируете дорешивать?

2023-01-07 13:26 UTC, illided commented
> Вы глобально до какой оценки планируете дорешивать?
Ну хотелось бы до четверки хотя бы)
Пять было бы неплохо но не уверен что баллов хватит

2023-01-07 13:43 UTC, Kakadu commented
> Ну хотелось бы до четверки хотя бы)

Сейчас максимальная С получается.

2023-01-07 14:15 UTC, Kakadu commented on Ruby/functions.t
> +  $ ./INTERPRET.exe ../../../../examples/combinators.rb
Добейте вот это, я помержу

2023-01-07 16:44 UTC, illided commented on Ruby/functions.t
> +  $ ./INTERPRET.exe ../../../../examples/combinators.rb
Готово

2023-01-07 18:41 UTC, merged