Bash | Kuzmina Kseniia
Kakadu/fp2022 pull request #53
Opened 2023-02-24 20:02 UTC by sayumikko

2023-02-25 13:37 UTC, Kakadu requested changes
Код интерпретатора мог бы быть написан лучше.

2023-02-25 13:37 UTC, Kakadu commented on bash/demos/demoInterpreter.t
> +  0
Два нуля в начале это подозрительно

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +  let from_val init = replace "0" init M.empty
M.singleton "0" ?

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +           }
Копипасту напоминает...

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +           }
А тут правда эти return нужны?

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +      | _ -> ""
Вложенные паттерны, не?

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +      | _ -> ""
И ниже тоже

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +    | _ :: _ :: tl -> interpret_bexp ctx tl [] >>= fun ctx -> return ctx
Где-то такое я уже видел....

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +      | _ -> return ""
matching_iconst было выше

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +      >>= fun s -> return { ctx with last_exec = Int (String.length s) }
С обновлением last_exec копипаста. Может её можно убрать?

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +      >>= fun pos ->
Я там про let* рассказывал. Вы не осилили или так правда больше нравится?

2023-02-25 13:37 UTC, Kakadu commented on bash/lib/interpreter.ml
> +    | [] -> return ctx
Тут много где просится функция, которая делает монадический fold
`foldm : ('a m -> 'b -> 'a m) -> 'a m -> 'b list -> 'a m`
Она должна много чего упростить

2023-02-25 14:55 UTC, sayumikko commented on bash/lib/interpreter.ml
> +    | [] -> return ctx
Здравствуйте! В этих функциях иногда необходимо возвращать контекст и сразу останавливаться. Мне кажется, что foldM такого не позволяет.

2023-02-25 14:56 UTC, sayumikko commented on bash/demos/demoInterpreter.t
> +  0
Ошибка была в тесте, поправила

2023-02-25 14:57 UTC, sayumikko commented on bash/lib/interpreter.ml
> +  let from_val init = replace "0" init M.empty
Работает, спасибо

2023-02-25 14:58 UTC, sayumikko commented on bash/lib/interpreter.ml
> +           }
Немного почистила код, и правда аккуратнее смотрится

2023-02-26 11:55 UTC, Kakadu approved these changes
Ещё можно было бы попридираться, что большее количество let* может ещё подсократить, и что надо бы больше тестов на пайпы, ну да ладно.

> Здравствуйте! В этих функциях иногда необходимо возвращать контекст и сразу останавливаться. Мне кажется, что foldM такого не позволяет.

Можно написать CPSный foldm, который это умеет. Вам и так, и так разбираться с этой темой для теорэкзамена.

2023-02-26 11:55 UTC, merged

2023-02-26 11:55 UTC, Kakadu commented
Вроде на макс. С накопилось.