Make
Kakadu/fp2022 pull request #57
Opened 2023-03-13 11:19 UTC by ioannessh

Сделано:

- АСД
- Парсел с поддержком переноса строк, но без поддержки комментариев
- Интерпритатор с обходом графа, игнорированием циклов и подстановкой ппеременных
- Тесты для парсера
- pretty printer

2023-03-13 21:36 UTC, Kakadu commented on make/README.md
> +
Мне ещё ни разу не присылали README с таким количество опечаток

2023-03-13 21:37 UTC, Kakadu commented on make/demos/demo_project/hello_world1.cpp
> +#include <stdlib.h>
Много лишних include.

2023-03-13 21:39 UTC, Kakadu commented on make/lib/dune
> + (libraries base angstrom unix core ocamlgraph graphlib)
Обе либы для графов? Это точно не избыточно?

2023-03-13 21:39 UTC, Kakadu commented on make/lib/interpret.ml
> +exception AllDone
Я от народа хочу монадический интерпретатор, а тут пачка исключений.

2023-03-13 21:40 UTC, Kakadu commented on make/lib/interpret.ml
> +    then VMap.update target (fun l -> Some (List.concat [ prereqs; Option.get l ])) map
concat какой-то очень сложный

2023-03-13 21:42 UTC, Kakadu commented on make/lib/interpret.ml
> +  let echo command = Sys.command (String.concat " " [ "echo"; command ]) in
А точно нужно вызывать echo, чтобы строчку напечатать?

2023-03-13 21:42 UTC, Kakadu commented on make/lib/interpret.ml
> +  let vars_map = VMap.update "@" (fun _ -> Some target) vars_map in
Это магическая строковая константа?

2023-03-13 21:44 UTC, Kakadu requested changes
Что-то я не нашел ни одного теста.
И монады вы не осилили.

2023-03-13 21:44 UTC, Kakadu commented on make/lib/parser.ml
> +  | Error e -> raise (InvalidString (input, e))
Вы определенно не осилили монады.

2023-03-14 08:22 UTC, ioannessh commented on make/lib/interpret.ml
> +  let vars_map = VMap.update "@" (fun _ -> Some target) vars_map in
Я так автоматические переменные задаю

2023-03-14 08:29 UTC, ioannessh commented on make/lib/parser.ml
> +  | Error e -> raise (InvalidString (input, e))
Я только у парсера написал тесты у некоторых функций. Какие тесты ещё надо добавить?

2023-03-14 09:24 UTC, ioannessh commented on make/lib/interpret.ml
> +exception AllDone
Они, кроме последнего, происходят в графе. И я не знаю как можно по другому сделать.

2023-03-14 09:26 UTC, ioannessh commented on make/lib/dune
> + (libraries base angstrom unix core ocamlgraph graphlib)
ocamlgraph лишний, можно без него

2023-03-17 12:15 UTC, Kakadu commented on make/demos/tests/timestat/all
А пустые файлы эти точно нужны?

2023-03-18 08:23 UTC, Kakadu commented
Е

2023-03-18 08:23 UTC, merged