Implement mini Cypher interpreter | Drumov Maxim
Kakadu/fp2022 pull request #59
Opened 2023-03-14 16:13 UTC by DrumovMax

Features done:
- Cypher AST
- Cypher Parser
- Cypher Interpreter
- Implemented commands:
  - CREATE used to create nodes and edges;
  - MATCH Used to set the search parameters for the graph. In MATCH and CREATE, you can create and query edges both ways: ()-->() and ()<--(), multiedges ()-->()<--() queries are not supported;
  - WHERE serves as a label and property check. WHERE is always used with MATCH;
  - DETACH DELETE used to remove nodes and edges. When you delete a node, all edges connected to it are deleted;
  - DELETE is used to remove nodes and edges. You can only delete nodes that have no ties.

2023-03-16 17:11 UTC, Kakadu requested changes
Тут очень много синтаксического мусора в виде дестких ошибок. Исправляйте.

2023-03-16 17:11 UTC, Kakadu commented on Cypher/lib/interpret.ml
> +  | n, e ->
let would be better.

2023-03-16 22:32 UTC, DrumovMax commented on Cypher/lib/interpret.ml
> +      match List.hd valuelist with
Не совсем понял вопроса. Исправил как понял(

2023-03-16 22:35 UTC, DrumovMax commented on Cypher/lib/interpret.ml
> +            let ret value = return @@ valuelist @ [ cval value ] in
Изменил на обычное добавление элемента к списку. После реверс листа выдает результаты поиска в правильном порядке(раньше выдавало криво в обратном порядке)

2023-03-17 11:39 UTC, Kakadu commented on Cypher/lib/ast.ml
> +type direction = string option * string option * property list option
Если вы думаете, что это что-то поясняет -- нет.

2023-03-17 11:40 UTC, Kakadu commented on Cypher/lib/interpret.ml
> +  | UnstableElm
А что такое "нестабильность" в терминах Cypher?

2023-03-17 11:40 UTC, Kakadu commented on Cypher/lib/interpret.ml
> +and values =
Ненужная рекурсия?

2023-03-17 11:42 UTC, Kakadu commented on Cypher/lib/interpret.ml
> +and elm = (vlabels * vprops) * (node_src_dst option * node_src_dst option)
Это какой-то стремный дизайн. Что означает, если там None и Some?

2023-03-17 11:48 UTC, Kakadu reviewed
Вроде неплохо. Вы сколько за это хотите?

2023-03-17 13:22 UTC, DrumovMax commented on Cypher/lib/interpret.ml
> +and elm = (vlabels * vprops) * (node_src_dst option * node_src_dst option)
Рассматриваются только варианты (None, None) и (Some, Some). Так проще хранить в одном энве и узлы и ребра. (None, None) - означает что это узел. (Some, Some) - это ребро которое хранит данные о узле из которого выходит ребро и в какой узел входит.

2023-03-17 14:27 UTC, DrumovMax commented on Cypher/lib/interpret.ml
> +  | UnstableElm
Ошибка нужна для случаев когда в MATCH не пишется информация о узле между узлами и тогда ребро все равно добавляется в энв и поиск в WHERE не ломается. То есть можно любое имя написать для ребра, которое мы не определили и по этому имени искать propertу. Добавил тест, который показывает работу этого поиска

2023-03-17 14:28 UTC, DrumovMax commented on Cypher/lib/interpret.ml
> +and values =
Исправил

2023-03-17 14:29 UTC, DrumovMax commented on Cypher/lib/ast.ml
> +type direction = string option * string option * property list option
Описал более подробно

2023-03-18 08:27 UTC, Kakadu commented on Cypher/lib/interpret.ml
> +  | UnstableElm
А это нельзя было как-нить в AST запихнуть, чтобы не обрабатывать в интерпретаторе?

2023-03-18 08:28 UTC, Kakadu commented
Комментарий к UnstableElm говорит, что там походу какая-то халява совершена в дизайне AST. Мне лень сегодня разбираться, что там да как, поэтому С, которую я планировал изначально стоит снизить до D.

2023-03-18 08:29 UTC, merged