Pascal | Kazancev Anton
Kakadu/fp2022 pull request #9
Opened 2022-10-28 00:03 UTC by toxakaz

AST, parser, semantic test and interpreter

2022-10-28 13:05 UTC, Kakadu commented on Pascal/lib/ast.mli
> +  | VTArray of expr * expr * vtype (** array type with expr..expr interval *)
А там правда произвольные выражения, а не константы?

2022-10-28 13:29 UTC, Kakadu requested changes
Тут вроде есть какой-то прогресс, но пока не всё хорошо. 
Как минимум тесты на рекурсию нужны, и ещё я хотел бы вспомнить какое там условие было

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/ast.mli
> +  | DDConst of name * value (** const definition by value *)
А в чем разница между DConst  и DDConst. Я не совсем понимаю,что такое value, наверное....

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/ast.mli
> +[@@deriving show]
Я без понятия что это.

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/exceptions.ml
> +exception RealizationError
Скорее всего это исключение -- признак говнокода

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/imArray.mli
> +    | Empty of int * 'a
Без понятния, что такое второй конструктор

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/interpreter.mli
> +
Там есть стандартный тип Result.С ним будет лучше.

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/keyMap.ml
> +module KeyMap = Map.Make (String)
Если здесь написать include вместо module, то всё можно подсократить

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/parser.ml
> +let cl2s cl = String.concat "" (List.map (String.make 1) cl)
https://docs.ocaml.pro/docs/LIBRARY.opal@opal.0.1.1/Opal/index.html#val-implode

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/vTypeBasics.ml
> +  in
А что за магическая константа 255?

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/interpreter.ml
> +let ( => ) arg f = f arg
Для этого есть каноничный оператор `|>`

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/interpreter.ml
> +  List.fold_left (fun b st -> b && eval_stmt_type ~loop w st) true
Это такой по-сложному написанный List.for_all?

2022-10-28 13:29 UTC, Kakadu commented on Pascal/lib/interpreter.ml
> +;;
Было бы круто ещё факториалы/фибоначчи увидеть как минимум, чтобы понять , что рекурсия работает.

2022-10-28 14:21 UTC, Kakadu requested changes

2022-10-28 14:21 UTC, Kakadu commented on Pascal/lib/ast.mli
> +  | ProcCall of expr (** procedure calling *)
???

2022-11-04 09:16 UTC, toxakaz commented on Pascal/lib/ast.mli
> +  | VTArray of expr * expr * vtype (** array type with expr..expr interval *)
Да.
Пример объявления массива с использованием выражений:
```
const n = 10;
var arr : array[0..n + 1] of integer;
```

2022-11-04 09:17 UTC, toxakaz commented on Pascal/lib/ast.mli
> +  | VTArray of expr * expr * vtype (** array type with expr..expr interval *)
Однако в таких выражениях нельзя использовать что то кроме констант и стандартных функций.

2022-11-04 09:22 UTC, toxakaz commented on Pascal/lib/ast.mli
> +  | DDConst of name * value (** const definition by value *)
expr - выражение. Пример: `1 + 2 * 3`.
value - значение. Пример `42`.

DConst - Define Const. Общий тип для объявления константы, хранящий выражение.
DDConst - Define DescribedConst. Тип для константы, выражение которой посчитано.

2022-11-04 09:25 UTC, toxakaz commented on Pascal/lib/ast.mli
> +[@@deriving show]
Во внутреннем представлении значение переменной может быть константой (VConst), изменяемым (VVariable), или переменная может быть описанием типа (VType): в этом случае значения у неё нет.

В поле с переменными лежат пары вида (vtype * variable) - посчитанный и неизменяемый тип (vtype) и значение (variable).

2022-11-04 09:28 UTC, toxakaz commented on Pascal/lib/exceptions.ml
> +exception RealizationError
Данное исключение использовалось в тех местах кода, попадание в которые значило что ошибка в самом интерпретаторе. Попадание туда зависит только от написания интерпретатора и не должно происходить, но ведь если вдруг произошло нужно что то сделать.

В любом случае, я избавился от этого исключения.

2022-11-04 09:29 UTC, toxakaz commented on Pascal/lib/imArray.mli
> +    | Empty of int * 'a
Массив, который создали но не разу не изменили, можно не выделять, а хранить его размер и значение, которым он должен быть заполнен.

2022-11-04 09:30 UTC, toxakaz commented on Pascal/lib/imArray.mli
> +    | Empty of int * 'a
Это полезно при семантическом анализе, в котором стандартные значения всем переменным инициализируются, но никогда не используются.

2022-11-04 09:30 UTC, toxakaz commented on Pascal/lib/interpreter.mli
> +
Стало луче.

2022-11-04 09:31 UTC, toxakaz commented on Pascal/lib/keyMap.ml
> +module KeyMap = Map.Make (String)
Сократил.

2022-11-04 09:32 UTC, toxakaz commented on Pascal/lib/parser.ml
> +let cl2s cl = String.concat "" (List.map (String.make 1) cl)
Воспользовался функцией `implode`.

2022-11-04 09:32 UTC, toxakaz commented on Pascal/lib/vTypeBasics.ml
> +  in
Стандартный размер строки в Паскале. Возможно его стоит куда то вынести в виде переменной.

2022-11-04 09:33 UTC, toxakaz commented on Pascal/lib/interpreter.ml
> +let ( => ) arg f = f arg
Исправил.

2022-11-04 09:33 UTC, toxakaz commented on Pascal/lib/interpreter.ml
> +  List.fold_left (fun b st -> b && eval_stmt_type ~loop w st) true
Да. Исправил.

2022-11-04 09:33 UTC, toxakaz commented on Pascal/lib/interpreter.ml
> +;;
Исправил.

2022-11-04 09:37 UTC, toxakaz commented on Pascal/lib/ast.mli
> +  | ProcCall of expr (** procedure calling *)
```
type
  intf = function : integer;    //объявление типа для хранения функции без аргументов, возвращающей integer.
var
  f_arr : array [0..10] of intf;
  function f : integer;
  begin
    f := 42;
  end;
begin
  f_arr[5] := f;
  f_arr[5]();        //вызов процедуры / функции, от выражения (взятие 5 индекса массива f_arr).
end.

2022-11-04 09:52 UTC, toxakaz commented on Pascal/lib/ast.mli
> +  | ProcCall of expr (** procedure calling *)
А по сути это аналогично выполнению выражения `f_arr[5]()`, так что не вижу смысла вводить какой то особый тип.

2022-11-09 09:45 UTC, Kakadu commented
Вам не кажется, что писать в маркдауне bullet listы на голом HTMLe, в то время как markdown сам умеет bullet списки... это бред?

2022-11-09 10:33 UTC, toxakaz commented
Да, прошу прощения. С html в readme увлёкся.

2022-11-09 19:06 UTC, Kakadu commented
Меня вот смущает такое огромное количетсво RuntimeError. По ихъ использованию совершенно невозможно понять, это вы накосчили, или входная программа плохая. По сути это даже хуже чем `failwith "string"`, потому что читателю невозможно понять, что пошло не так.
От остальных я монадический интерпретатор всегда требовал, где такой проблемы нет.

2022-11-09 19:59 UTC, toxakaz commented
После семантического анализа, у матчей в интерпретаторе появляется много недостижимого кода.

2022-11-09 20:20 UTC, Kakadu commented
> После семантического анализа, у матчей в интерпретаторе появляется много недостижимого кода.

Ну, объективно это гавнокод же

2022-11-09 21:04 UTC, toxakaz commented
Пересмотрел исключения. Убрал большую часть RuntimeError.

2022-11-11 13:08 UTC, Kakadu commented on Pascal/lib/interpreter.ml
> +    if not (cast_type l r) then raise (PascalInterp (InvalidType (l, r)))
Я вот смотрю и не понимаю, где в обработке присваивания непосредственно присваивание?

2022-11-11 13:28 UTC, toxakaz commented on Pascal/lib/interpreter.ml
> +    if not (cast_type l r) then raise (PascalInterp (InvalidType (l, r)))
Это проверка семантики

2022-11-11 13:31 UTC, toxakaz commented on Pascal/lib/interpreter.ml
> +    if not (cast_type l r) then raise (PascalInterp (InvalidType (l, r)))
statement -> unit
исполнится, если всё хорошо, вернёт ошибку, если не сходятся типы или есть некоторые другие проблемы.
окружение не меняется, так как у переменной не может измениться тип.

2022-11-11 13:33 UTC, toxakaz commented on Pascal/lib/interpreter.ml
> +    if not (cast_type l r) then raise (PascalInterp (InvalidType (l, r)))
Само присваивание здесь не обрабатывается. Оно обрабатывается далее в функции eval_stmt.

2022-11-11 16:29 UTC, merged